"""Pure domain metrics calculation and WhatsApp/email weekly summary formatting.

No FastAPI, no SQLAlchemy dependencies.
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class VenueMetrics:
    court_hours_used: float
    capacity_hours: float
    fill_rate_percent: float
    confirmed_players: int
    waitlist_demand: int
    new_players_count: int
    total_revenue_pesewas: int
    total_revenue_ghs: float
    unreported_matches_count: int


def calculate_venue_metrics(
    court_hours_used: float,
    capacity_hours: float,
    confirmed_players: int,
    waitlist_demand: int,
    new_players_count: int,
    total_revenue_pesewas: int,
    unreported_matches_count: int,
) -> VenueMetrics:
    """Calculate venue utilization rates and format monetary figures."""
    if capacity_hours > 0:
        fill_rate = round((court_hours_used / capacity_hours) * 100.0, 1)
    else:
        fill_rate = 0.0

    total_ghs = round(total_revenue_pesewas / 100.0, 2)

    return VenueMetrics(
        court_hours_used=court_hours_used,
        capacity_hours=capacity_hours,
        fill_rate_percent=fill_rate,
        confirmed_players=confirmed_players,
        waitlist_demand=waitlist_demand,
        new_players_count=new_players_count,
        total_revenue_pesewas=total_revenue_pesewas,
        total_revenue_ghs=total_ghs,
        unreported_matches_count=unreported_matches_count,
    )


def format_weekly_club_summary(
    venue_name: str,
    metrics: VenueMetrics,
    week_label: str,
) -> str:
    """Format one-page weekly summary ready to share via WhatsApp or email."""
    return (
        f"📊 *{venue_name} - Weekly Performance Summary*\n"
        f"📅 Period: {week_label}\n\n"
        f"🎾 Court Hours Used: {metrics.court_hours_used:.1f} hrs / {metrics.capacity_hours:.1f} hrs\n"
        f"📈 Fill Rate: {metrics.fill_rate_percent:.1f}%\n"
        f"👥 Confirmed Players: {metrics.confirmed_players}\n"
        f"⏳ Unmet Waitlist Demand: {metrics.waitlist_demand} players\n"
        f"✨ New Players Brought In: {metrics.new_players_count}\n"
        f"⚠️ Unreported Matches: {metrics.unreported_matches_count}\n"
        f"💰 Total Settlement: GH₵ {metrics.total_revenue_ghs:,.2f}\n\n"
        f"_Generated by Padel Ghana Platform for Club Organisers_"
    )
